# Use a minimal Node.js image as the base
FROM node:alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the contents of the current directory into the container
COPY . .



ENTRYPOINT ["node","run.js"]




# Run the Node.js script with arguments provided during runtime
